bt:
  portList:
  - 24678
  - 6881
  trackerList:
  - router.utorrent.com:6881
  - router.bittorrent.com:6881
  - router.bitcomet.com:6881
  - dht.transmissionbt.com:6881
  nodeQueueMaxLength: 409600
  findNodeTaskIntervalMS: 1
  serverEventLoopThreadNum: 600
  findNodeTaskThreadNum: 600
  handleGetPeersInfoHash: false

spring:
  datasource:
    url: jdbc:mysql://134.175.188.140/btcrawler?useSSL=false&characterEncoding=UTF-8
    password: 123456
    username: hxs
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com.hxs.bt: info